### PR TITLE
Addded Rust linter (rust-fmt)

### PR DESCRIPTION
**Pull request by jayavanth**
Linter for rust. rust-fmt should be installed from [here](https://github.com/rust-lang-nursery/rustfmt).

### CODE REVIEW

**Comment by epriestley** [comment]
https://secure.phabricator.com/book/phabcontrib/article/contributing_code/#no-pull-requests

**Comment by jayavanth** [comment]
@epriestley How do I open a task without having a login to phabricator?

**Comment by epriestley** [comment]
What have you tried, and what instructions have you found so far?

**Comment by jayavanth** [comment]
None of the logins work: github, facebook etc. The link that you sent asks the user to sign the CLA, which I did. It also asks that I submit a task, which requires a login, which is invite only.

**Pull request closed without merging**
